version: "3"
services:
  users:
    image: users
    build: users
    restart: unless-stopped
    ports:
      - 5000:5000
  forum:
    image: forum
    build: forum
    restart: unless-stopped
    ports:
      - 4000:4000
  findfriend:
    image: findfriend
    build: findfriend
    restart: unless-stopped
    ports:
      - 7000:7000
