version: "3"
services:
  users:
    image: users
    build: users
    restart: unless-stopped
    environment:
      USERS_DB_URL: ${USERS_DB_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      USERS_BACKEND_URL: ${USERS_BACKEND_URL}
      USERS_PORT: ${USERS_PORT}
      EMAIL: ${EMAIL}
      GCP_ACCESS_TOKEN: ${GCP_ACCESS_TOKEN}
      GCP_REFRESH_TOKEN: ${GCP_REFRESH_TOKEN}
      GCP_CLIENT_SECRET: ${GCP_CLIENT_SECRET}
      GCP_CLIENT_ID: ${GCP_CLIENT_ID}
      JWT_ACCESS_TOKEN: ${JWT_ACCESS_TOKEN}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_BUCKET_REGION: ${S3_BUCKET_REGION}
    ports:
      - 5000:5000
  forum:
    image: forum
    build: forum
    restart: unless-stopped
    environment:
      FORUM_DB_URL: ${FORUM_DB_URL}
      FORUM_PORT: ${FORUM_PORT}
      JWT_ACCESS_TOKEN: ${JWT_ACCESS_TOKEN}
    ports:
      - 4000:4000
  findfriend:
    image: findfriend
    build: findfriend
    restart: unless-stopped
    environment:
      FINDFRIEND_DB_URL: ${FINDFRIEND_DB_URL}
      FINDFRIEND_PORT: ${FINDFRIEND_PORT}
      JWT_ACCESS_TOKEN: ${JWT_ACCESS_TOKEN}
    ports:
      - 7000:7000
  chat:
    image: chat
    build: chat
    restart: unless-stopped
    environment:
      CHAT_PORT: ${CHAT_PORT}
    ports:
      - 9000:9000
