name: Backend Deployment (AWS EC2)

on:
  push:
    branches: [backend-CD]
  pull_request:
    branches: [backend-CD]
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

defaults:
  run:
    working-directory: ./backend
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker-compose build

      - name: AWS Configure
        run: |
          aws configure

      - name: Run script file
        shell: bash
        run: |
          chmod +x deploy.sh
          ./deploy.sh
