name: Backend Deployment (AWS EC2)

on:
  push:
    branches: [backend-CD]
  pull_request:
    branches: [backend-CD]
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

env: # .env config for backend
  # JWT
  JWT_ACCESS_TOKEN: ${{secrets.JWT_ACCESS_TOKEN}}
  # S3
  S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
  S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
  S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
  S3_BUCKET_REGION: ap-southeast-1
  # USERS MS
  USERS_DB_URL: ${{secrets.USERS_DB_URL}}
  FRONTEND_URL: http://nusocialife.net
  USERS_BACKEND_URL: http://localhost:5000/api/users
  USERS_PORT: 5000
  EMAIL: nusocialife28@gmail.com
  GCP_ACCESS_TOKEN: ${{secrets.GCP_ACCESS_TOKEN}}
  GCP_REFRESH_TOKEN: ${{secrets.GCP_REFRESH_TOKEN}}
  GCP_CLIENT_SECRET: ${{secrets.GCP_CLIENT_SECRET}}
  GCP_CLIENT_ID: ${{secrets.GCP_CLIENT_ID}}
  # FORUM MS
  FORUM_DB_URL: ${{secrets.FORUM_DB_URL}}
  FORUM_PORT: 4000
  # FINDFRIEND MS
  FINDFRIEND_DB_URL: ${{secrets.FINDFRIEND_DB_URL}}
  FINDFRIEND_PORT: 7000
  # CHAT MS
  CHAT_PORT: 9000

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2

      - name: Create Users env file
        run: |
          touch ./users/.env
          echo USERS_DB_URL=${{ env.USERS_DB_URL }} >> .env
          echo FRONTEND_URL=${{ env.FRONTEND_URL }} >> .env
          echo USERS_BACKEND_URL=${{ env.USERS_BACKEND_URL }} >> .env
          echo USERS_PORT=${{ env.USERS_PORT }} >> .env
          echo EMAIL=${{ env.EMAIL }} >> .env
          echo GCP_ACCESS_TOKEN=${{ env.GCP_ACCESS_TOKEN }} >> .env
          echo GCP_REFRESH_TOKEN=${{ env.GCP_REFRESH_TOKEN }} >> .env
          echo GCP_CLIENT_SECRET=${{ env.GCP_CLIENT_SECRET }} >> .env
          echo GCP_CLIENT_ID=${{ env.GCP_CLIENT_ID }} >> .env
          echo JWT_ACCESS_TOKEN=${{ env.JWT_ACCESS_TOKEN }} >> .env
          echo S3_ACCESS_KEY_ID=${{ env.S3_ACCESS_KEY_ID }} >> .env
          echo S3_SECRET_ACCESS_KEY=${{ env.S3_SECRET_ACCESS_KEY }} >> .env
          echo S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }} >> .env
          echo S3_BUCKET_REGION=${{ env.S3_BUCKET_REGION }} >> .env
          cat .env

      - name: Create Forum env file
        run: |
          touch ./forum/.env
          echo FORUM_DB_URL=${{ env.FORUM_DB_URL }} >> .env
          echo FORUM_PORT=${{ env.FORUM_PORT }} >> .env
          echo JWT_ACCESS_TOKEN=${{ env.JWT_ACCESS_TOKEN }} >> .env
          cat .env

      - name: Create findFriend env file
        run: |
          touch ./findfriend/.env
          echo FINDFRIEND_DB_URL=${{ env.FINDFRIEND_DB_URL }} >> .env
          echo FINDFRIEND_PORT=${{ env.FINDFRIEND_PORT }} >> .env
          echo JWT_ACCESS_TOKEN=${{ env.JWT_ACCESS_TOKEN }} >> .env
          cat .env

      - name: Create chat env file
        run: |
          touch ./chat/.env
          echo CHAT_PORT=${{ env.CHAT_PORT }} >> .env
          cat .env

      - name: Docker Build
        run: |
          docker-compose build

      - name: AWS Configure
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.S3_BUCKET_REGION }}

      - name: Run script file
        shell: bash
        run: |
          chmod +x deploy.sh
          ./deploy.sh
