name: Frontend Deployment (AWS Amplify)

on:
  push:
    branches: [ frontend-amplifyCD ] #master
  pull_request:
    branches: [ frontend-amplifyCD ] #master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./frontend
jobs:
  deploy:
    env:
        amplifyVersion: 'latest'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          
      # Install node_modules dependencies for frontend
      - name: install frontend dependencies
        run: npm install
      
      # Set up and linking to AWS Amplify
      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          project_dir: './frontend'
          amplify_cli_version: ${{ env.amplifyVersion }}
          amplify_command: configure
          amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      
      # Deployment to Amplify
      - name: deploy to amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          project_dir: './frontend'
          amplify_cli_version: ${{ env.amplifyVersion }}
          amplify_command: publish
          amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}